CREATE TABLE farWebfeed(
keywords varchar(250) NULL DEFAULT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
itunesauthor varchar(250) NULL DEFAULT NULL ,
bAuthor tinyint(1) NULL DEFAULT 0 ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
skiphours varchar(250) NULL DEFAULT NULL ,
itunescategories varchar(250) NULL DEFAULT NULL ,
itunessubtitleproperty varchar(250) NULL DEFAULT NULL ,
url varchar(250) NULL DEFAULT NULL ,
generator varchar(250) NULL DEFAULT 'http://www.farcrycms.org/' ,
copyright varchar(250) NULL DEFAULT NULL ,
itunesimage varchar(250) NULL DEFAULT NULL ,
itemtype varchar(250) NULL DEFAULT NULL ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
atomicon varchar(250) NULL DEFAULT NULL ,
subtitle varchar(250) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
description varchar(250) NULL DEFAULT NULL ,
dateproperty varchar(250) NULL DEFAULT 'datetimecreated' ,
keywordsproperty varchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
language varchar(250) NULL DEFAULT NULL ,
feedimage varchar(250) NULL DEFAULT NULL ,
enclosurefileproperty varchar(250) NULL DEFAULT NULL ,
iTunesFeedId decimal(11,0) NULL ,
directory varchar(250) NULL DEFAULT NULL ,
catFilter longtext NULL ,
createdby varchar(250) NOT NULL DEFAULT '' ,
contentproperty varchar(250) NULL DEFAULT 'teaser' ,
datetimecreated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
skipdays varchar(250) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
editoremail varchar(250) NULL DEFAULT NULL ,
editor varchar(250) NULL DEFAULT NULL ,
itunesdurationproperty varchar(250) NULL DEFAULT NULL ,
title varchar(250) NULL DEFAULT NULL ,
titleproperty varchar(250) NULL DEFAULT 'title' ,
ownedby varchar(250) NULL DEFAULT NULL 
);
