CREATE TABLE dmArchive(
metaWDDX ntext NULL ,
datetimelastupdated datetime NOT NULL ,
objectTypename nvarchar(250) NULL DEFAULT NULL ,
lockedBy nvarchar(250) NULL DEFAULT NULL ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
bDeleted bit NULL DEFAULT 0 ,
datetimecreated datetime NOT NULL ,
archiveID nvarchar(50) NULL DEFAULT NULL ,
event nvarchar(250) NULL DEFAULT NULL ,
locked bit NOT NULL DEFAULT 0 ,
lRoles nvarchar(250) NULL DEFAULT NULL ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
objectWDDX ntext NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
ipaddress nvarchar(250) NULL DEFAULT NULL ,
ownedby nvarchar(250) NULL DEFAULT NULL ,
username nvarchar(250) NULL DEFAULT NULL 
);
