CREATE TABLE farImageGallery(
imgCoverSourceID nvarchar(50) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
lockedBy nvarchar(250) NULL DEFAULT NULL ,
imgCover nvarchar(250) NULL DEFAULT NULL ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
datetimecreated datetime NOT NULL ,
catImageGallery ntext NULL ,
status nvarchar(250) NOT NULL DEFAULT 'draft' ,
locked bit NOT NULL DEFAULT 0 ,
teaser ntext NULL ,
displayMethod nvarchar(250) NOT NULL DEFAULT 'displayPageStandard' ,
SourceID nvarchar(50) NULL DEFAULT NULL ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
title nvarchar(250) NULL DEFAULT NULL ,
versionID nvarchar(50) NULL DEFAULT NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
Body ntext NULL ,
ownedby nvarchar(250) NULL DEFAULT NULL 
);
