CREATE TABLE farWorkflow(
bTasksComplete tinyint(1) NULL DEFAULT 0 ,
referenceID varchar(50) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
completionDate datetime NULL DEFAULT NULL ,
bActive tinyint(1) NULL DEFAULT 1 ,
workflowDefID varchar(50) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
createdby varchar(250) NOT NULL DEFAULT '' ,
datetimecreated datetime NOT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
bWorkflowSetupComplete tinyint(1) NULL DEFAULT 0 ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
bWorkflowComplete tinyint(1) NULL DEFAULT 0 ,
title varchar(250) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
ownedby varchar(250) NULL DEFAULT NULL ,
description longtext NULL 
);
