CREATE TABLE dmArchive(
metaWDDX longtext NULL ,
datetimelastupdated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
objectTypename varchar(250) NULL DEFAULT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
createdby varchar(250) NOT NULL DEFAULT '' ,
bDeleted tinyint(1) NULL DEFAULT 0 ,
datetimecreated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
archiveID varchar(50) NULL DEFAULT NULL ,
event varchar(250) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
lRoles varchar(250) NULL DEFAULT NULL ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
objectWDDX longtext NULL ,
label varchar(250) NULL DEFAULT NULL ,
ipaddress varchar(250) NULL DEFAULT NULL ,
ownedby varchar(250) NULL DEFAULT NULL ,
username varchar(250) NULL DEFAULT NULL 
);
