CREATE TABLE dmNews(
datetimelastupdated datetime NOT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
catNews longtext NULL ,
source varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
expiryDate datetime NULL DEFAULT NULL ,
createdby varchar(250) NOT NULL DEFAULT '' ,
datetimecreated datetime NOT NULL ,
status varchar(250) NOT NULL DEFAULT 'draft' ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
Teaser varchar(2000) NULL DEFAULT NULL ,
displayMethod varchar(250) NOT NULL DEFAULT 'displayPageStandard' ,
publishDate datetime NULL DEFAULT NULL ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
teaserImage varchar(50) NULL DEFAULT NULL ,
title varchar(250) NULL DEFAULT NULL ,
versionID varchar(50) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
Body longtext NULL ,
ownedby varchar(250) NULL DEFAULT NULL 
);
