CREATE TABLE dmHTML(
reviewDate datetime NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
lockedBy varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
createdby varchar(250) NOT NULL DEFAULT '' ,
catHTML varchar(250) NULL DEFAULT NULL ,
datetimecreated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
metaKeywords longtext NULL ,
status varchar(250) NOT NULL DEFAULT 'draft' ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
seoTitle varchar(250) NULL DEFAULT NULL ,
Teaser longtext NULL ,
displayMethod varchar(250) NOT NULL DEFAULT 'displayPageStandard' ,
extendedmetadata longtext NULL ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
teaserImage varchar(50) NULL DEFAULT NULL ,
Title varchar(250) NULL DEFAULT NULL ,
versionID varchar(50) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
Body longtext NULL ,
ownedby varchar(250) NULL DEFAULT NULL 
);
