CREATE TABLE dmCron(
datetimelastupdated datetime NOT NULL ,
lockedBy varchar(250) NULL DEFAULT NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
endDate datetime NOT NULL ,
createdby varchar(250) NOT NULL DEFAULT '' ,
startDate datetime NOT NULL ,
datetimecreated datetime NOT NULL ,
parameters varchar(250) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
template varchar(250) NULL DEFAULT NULL ,
bAutoStart tinyint(1) NOT NULL DEFAULT 1 ,
frequency varchar(250) NULL DEFAULT 'daily' ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
timeOut decimal(11,0) NULL DEFAULT 60 ,
title varchar(250) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
ownedby varchar(250) NULL DEFAULT NULL ,
description longtext NULL 
);
