CREATE TABLE farWorkflow(
bTasksComplete bit NULL DEFAULT 0 ,
referenceID nvarchar(50) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
lockedBy nvarchar(250) NULL DEFAULT NULL ,
completionDate datetime NULL DEFAULT NULL ,
bActive bit NULL DEFAULT 1 ,
workflowDefID nvarchar(50) NULL DEFAULT NULL ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
datetimecreated datetime NOT NULL ,
locked bit NOT NULL DEFAULT 0 ,
bWorkflowSetupComplete bit NULL DEFAULT 0 ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
bWorkflowComplete bit NULL DEFAULT 0 ,
title nvarchar(250) NULL DEFAULT NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
ownedby nvarchar(250) NULL DEFAULT NULL ,
description ntext NULL 
);
