CREATE TABLE dmProfile(
lockedBy varchar(250) NULL DEFAULT NULL ,
bActive tinyint(1) NOT NULL DEFAULT 0 ,
lastLogin datetime NULL DEFAULT NULL ,
notes longtext NULL ,
userDirectory varchar(250) NOT NULL DEFAULT '' ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
department varchar(250) NULL DEFAULT NULL ,
locale varchar(250) NOT NULL DEFAULT 'en_AU' ,
avatar varchar(250) NULL DEFAULT NULL ,
ObjectID varchar(50) NOT NULL DEFAULT '' ,
firstName varchar(250) NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
userName varchar(250) NOT NULL DEFAULT '' ,
emailAddress varchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL ,
bReceiveEmail tinyint(1) NOT NULL DEFAULT 1 ,
position varchar(250) NULL DEFAULT NULL ,
lastName varchar(250) NULL DEFAULT NULL ,
createdby varchar(250) NOT NULL DEFAULT '' ,
fax varchar(250) NULL DEFAULT NULL ,
wddxPersonalisation longtext NULL ,
datetimecreated datetime NOT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
overviewHome varchar(250) NULL DEFAULT NULL ,
phone varchar(250) NULL DEFAULT NULL ,
ownedby varchar(250) NULL DEFAULT NULL 
);
