CREATE TABLE farQueueTask(
datetimelastupdated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
lockedBy varchar(250) NULL DEFAULT NULL ,
wddxStackTrace longtext NULL ,
lastupdatedby varchar(250) NOT NULL DEFAULT '' ,
createdby varchar(250) NOT NULL DEFAULT '' ,
datetimecreated datetime NOT NULL DEFAULT '2214-05-29 04:10:36' ,
jobID varchar(50) NULL DEFAULT NULL ,
locked tinyint(1) NOT NULL DEFAULT 0 ,
taskOwnedBy varchar(250) NULL DEFAULT NULL ,
threadID varchar(50) NULL DEFAULT NULL ,
objectid varchar(50) NOT NULL DEFAULT '' ,
jobType varchar(250) NULL DEFAULT 'Unkown' ,
wddxDetails longtext NULL ,
action varchar(250) NULL DEFAULT NULL ,
taskTimestamp datetime NULL DEFAULT NULL ,
label varchar(250) NULL DEFAULT NULL ,
ownedby varchar(250) NULL DEFAULT NULL ,
taskStatus varchar(250) NULL DEFAULT NULL 
);
