CREATE TABLE dmProfile(
lockedBy nvarchar(250) NULL DEFAULT NULL ,
bActive bit NOT NULL DEFAULT 0 ,
lastLogin datetime NULL DEFAULT NULL ,
notes nvarchar(MAX) NULL ,
userDirectory nvarchar(250) NOT NULL DEFAULT '' ,
lastupdatedby nvarchar(250) NOT NULL DEFAULT '' ,
department nvarchar(250) NULL DEFAULT NULL ,
locale nvarchar(250) NOT NULL DEFAULT 'en_AU' ,
avatar nvarchar(250) NULL DEFAULT NULL ,
ObjectID nvarchar(50) NOT NULL DEFAULT '' ,
firstName nvarchar(250) NULL DEFAULT NULL ,
label nvarchar(250) NULL DEFAULT NULL ,
userName nvarchar(250) NOT NULL DEFAULT '' ,
emailAddress nvarchar(250) NULL DEFAULT NULL ,
datetimelastupdated datetime NOT NULL DEFAULT {ts '2214-05-29 16:10:36'} ,
bReceiveEmail bit NOT NULL DEFAULT 1 ,
position nvarchar(250) NULL DEFAULT NULL ,
lastName nvarchar(250) NULL DEFAULT NULL ,
createdby nvarchar(250) NOT NULL DEFAULT '' ,
fax nvarchar(250) NULL DEFAULT NULL ,
wddxPersonalisation nvarchar(MAX) NULL ,
datetimecreated datetime NOT NULL DEFAULT {ts '2214-05-29 16:10:36'} ,
locked bit NOT NULL DEFAULT 0 ,
overviewHome nvarchar(250) NULL DEFAULT NULL ,
phone nvarchar(250) NULL DEFAULT NULL ,
ownedby nvarchar(250) NULL DEFAULT NULL 
);
