INSERT INTO dmNews (datetimelastupdated,lockedBy,catNews,source,lastupdatedby,expiryDate,createdby,datetimecreated,status,locked,Teaser,displayMethod,publishDate,ObjectID,teaserImage,title,versionID,label,Body,ownedby) VALUES ('2013-12-31 13:29:55','','686932F0-0220-11E2-A52AD49A20F783BA','demo','farcry_CLIENTUD',NULL,'farcry_CLIENTUD','2013-12-19 14:54:35','approved',0,'News can be embargoed or forward published. This means that the news is approved, but not visible until some future date.','displayPageStandard','2015-07-04 14:54:00','44CDA0D0-6861-11E3-977B60C547035CDE','EAEFE5F0-685B-11E3-977B60C547035CDE','Embargoed or Forward Published News','','Embargoed or Forward Published News','<p>News can be embargoed or forward published. This means that the news is approved, but not visible until some future date.</p>','CDD3B33E-A463-9B75-DC0150D316830765');
INSERT INTO dmNews (datetimelastupdated,lockedBy,catNews,source,lastupdatedby,expiryDate,createdby,datetimecreated,status,locked,Teaser,displayMethod,publishDate,ObjectID,teaserImage,title,versionID,label,Body,ownedby) VALUES ('2013-12-19 15:47:39','','D6CCBA50-021B-11E2-9253D49A20F783BA','Vimeo','farcry_CLIENTUD',NULL,'farcry_CLIENTUD','2013-12-19 12:23:55','approved',0,'Glitch Game Teaser for new game company Tiny Speck. Glitch has got some beauty, sure. And, you are welcome to help yourself to some of it.','displayPageStandard','2013-12-19 12:23:00','3BA43FB0-684C-11E3-977B60C547035CDE','17D67490-685B-11E3-977B60C547035CDE','Glitch Game Teaser Vimeo Embed','','Glitch Game Teaser Vimeo Embed','<p>http://vimeo.com/10601444</p>
<p>Glitch Game Teaser for new game company Tiny Speck. Glitch has got some beauty, sure. And, you are welcome to help yourself to some of it.</p>','CDD3B33E-A463-9B75-DC0150D316830765');
INSERT INTO dmNews (datetimelastupdated,lockedBy,catNews,source,lastupdatedby,expiryDate,createdby,datetimecreated,status,locked,Teaser,displayMethod,publishDate,ObjectID,teaserImage,title,versionID,label,Body,ownedby) VALUES ('2013-12-19 15:01:25','','D6CCBA50-021B-11E2-9253D49A20F783BA','demo','farcry_CLIENTUD',NULL,'farcry_CLIENTUD','2013-12-06 14:26:53','approved',0,'Images can be embedded in the body content by Contributors or alternatively, you can design your templates to output your images dynamically.','displayPageStandard','2013-12-19 14:26:00','3FDD1AF0-5E26-11E3-8B7860C547035CDE','17D67496-685B-11E3-977B60C547035CDE','Just another day in Glitch','','Just another day in Glitch','<p><img src="/images/dmImage/StandardImage/Glitch%5FSmugglers%5F1920x10801%2Ejpg" border="0" alt="A Meeting of Smugglers to Distribute the Contraband" width="860" height="483" /></p>
<p>Images can be embedded in the body content by Contributors or alternatively, you can design your templates to output your images dynamically.</p>
<p><img src="/images/dmImage/StandardImage/Glitch%5FMeal%5FVendor%5F1920x10801%2Ejpg" border="0" alt="The Meal Vendor Gets an Early Start to His Day" width="860" height="483" /></p>
<p>It depends a little bit on how much flexibility you want to give contributors, and what your overall content strategy is.</p>','CDD3B33E-A463-9B75-DC0150D316830765');
INSERT INTO dmNews (datetimelastupdated,lockedBy,catNews,source,lastupdatedby,expiryDate,createdby,datetimecreated,status,locked,Teaser,displayMethod,publishDate,ObjectID,teaserImage,title,versionID,label,Body,ownedby) VALUES ('2013-12-19 14:54:21','','','','farcry_CLIENTUD',NULL,'farcry_CLIENTUD','2013-10-17 11:06:19','draft',0,'Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals.','displayPageStandard','2013-10-16 11:06:00','F24A35D0-36BF-11E3-AD5860C547035CDE','','Here is the news in draft','','Here is the news in draft','<p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman''s earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
<p>We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win.</p>
<p>We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win.</p>
<p>The dreams of yesterday are the hopes of today and the reality of tomorrow.</p>
<p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman''s earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>','CDD3B33E-A463-9B75-DC0150D316830765');
INSERT INTO dmNews (datetimelastupdated,lockedBy,catNews,source,lastupdatedby,expiryDate,createdby,datetimecreated,status,locked,Teaser,displayMethod,publishDate,ObjectID,teaserImage,title,versionID,label,Body,ownedby) VALUES ('2013-12-19 14:54:03','','','demo','farcry_CLIENTUD',NULL,'farcry_CLIENTUD','2013-12-19 14:53:14','pending',0,'Content can be approved directly or through a workflow process depending on what you need.','displayPageStandard','2013-12-19 14:53:00','147D01A0-6861-11E3-977B60C547035CDE','','And this News is pending approval','','And this News is pending approval','<p>Content can be approved directly or through a workflow process depending on what you need.</p>','CDD3B33E-A463-9B75-DC0150D316830765');
INSERT INTO dmNews (datetimelastupdated,lockedBy,catNews,source,lastupdatedby,expiryDate,createdby,datetimecreated,status,locked,Teaser,displayMethod,publishDate,ObjectID,teaserImage,title,versionID,label,Body,ownedby) VALUES ('2013-12-19 14:48:40','','686932F0-0220-11E2-A52AD49A20F783BA','Tiny Speck','farcry_CLIENTUD',NULL,'farcry_CLIENTUD','2013-12-19 14:42:12','approved',0,'The new promo trailer for Glitch that didn''t quite get finished until after the decision to shut it down was already made. Warning: may cause pangs of regret, longing and/or feelings of grief. But, it''s still nice to watch :)','displayPageStandard','2013-12-19 14:00:00','8A906EB0-685F-11E3-977B60C547035CDE','17D67495-685B-11E3-977B60C547035CDE','Game of Giant Imagination','','Game of Giant Imagination','<p>Embedding YouTube video is easy; just copy the link to your YouTube video into the body content of your page. You can even do multiple videos.</p>
<p>http://www.youtube.com/watch?v=PTGpRhJe5E0</p>
<p>The new promo trailer for Glitch that didn''t quite get finished until after the decision to shut it down was already made. Warning: may cause pangs of regret, longing and/or feelings of grief. But, it''s still nice to watch :)</p>
<p>http://www.youtube.com/watch?v=vuDYhczbqEQ</p>','CDD3B33E-A463-9B75-DC0150D316830765');

